services:
    ros_cudagl:
        build:
            args:
                ROS_TAG: ${ROS_TAG}
                OPENGL_TAG: ${OPENGL_TAG}
                CUDA_TAG: ${CUDA_TAG}
            context: .
            dockerfile: Dockerfile
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities:
                            - gpu
        env_file:
            - .env
        environment:
            - "DISPLAY=${DISPLAY}"
            - "QT_X11_NO_MITSHM=1"
        image: ros_cudagl:${ROS_TAG}_${CUDA_TAG}
        # For "Failed to initialize NVML: Unknown Error"
        privileged: true
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
