services:
    ros_cudagl:
        build:
            args:
                ROS_TAG: ${ROS_TAG}
                CUDAGL_TAG: ${CUDAGL_TAG}
            context: .
            dockerfile: Dockerfile
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        env_file:
            - .env
        environment:
            - "DISPLAY=${DISPLAY}"
            - "QT_X11_NO_MITSHM=1"
        image: ros_cudagl:${ROS_TAG}_${CUDAGL_TAG}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
